### ISSUE TITLE
Running input example for 10x CNV-analysis (runs up to step three)

### ISSUE THREAD

**Issue by floriankreten** [limin321/stmut#4]
Not sure if my input is in correct shape, or if this is a bug. Thanks in advance :)

Therefore, could you please provide a running example for input of 10x data for the CNV-caller (annotate, filtered, graph-based, positions)? I followed the given instructions (to my best knowledge), but only reach

Step 3, running cnvkit import-rna to infer CNV from RNA-seq data...
Dropping 16348 / 17943 rarely expressed genes from input samples
Loading gene metadata and TCGA gene expression/CNV profiles
Loaded /usr/local/bin/ensembl-gene-info.hg38.tsv with shape: (221323, 9)
Loaded /usr/local/bin/tcga-skcm.cnv-expr-corr.tsv with shape: (19177, 4)
Resetting 2846 ambiguous genes' correlation coefficients to default 0.100000
Trimmed gene info table to shape: (63966, 13)
Aligning gene info to sample gene counts
Weighting genes with below-average read counts
Calculating normalized gene read depths
Traceback (most recent call last):
  File "/usr/local/bin/cnvkit.py", line 9, in <module>
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/cnvlib/commands.py", line 1546, in _cmd_import_rna
    all_data, cnrs = import_rna.do_import_rna(
  File "/usr/local/lib/python3.10/dist-packages/cnvlib/import_rna.py", line 38, in do_import_rna
    gene_info, sample_counts, sample_data_log2 = rna.align_gene_info_to_samples(
  File "/usr/local/lib/python3.10/dist-packages/cnvlib/rna.py", line 270, in align_gene_info_to_samples
    sample_depths_log2 = normalize_read_depths(sc.divide(gi['tx_length'],
  File "/usr/local/lib/python3.10/dist-packages/cnvlib/rna.py", line 308, in normalize_read_depths
    assert sample_depths.values.sum() > 0
AssertionError

**Comment by floriankreten** [comment]
Thanks for your help Limin :) The problem was that my counts-matrix used the gene name, however you need to use the Ensembl ID.
